### ISSUE TITLE
Add Arts & Life section to home screen

### ISSUE THREAD

**Issue by MatthewTurk247** [TheStanfordDaily/stanforddaily-mobile#283]
Reference #282 and build something similar. For the title of the section, it suffices just to spell out the name of the section, but if you want to go the extra mile, replace the text with a blackened version of the attached image.
![artsAndLife](https://user-images.githubusercontent.com/9896143/97051782-65379400-1545-11eb-81ff-f06717f670bc.png)

**Comment by fibanneacci** [comment]
Sorry for the delay in doing this—I committed the changes to the dev branch (also forgot to add a commit message, but they're under the "Update Headlines.js" commit); they should be under @lilliansun's last PR
